### ISSUE TITLE
Doesn't send the right singnal

### ISSUE THREAD

**Issue by Vithop** [CardboardBread/Arduino-Game#3]

**Comment by CardboardBread** [comment]
My first guess is to try reversing the signal, making bit3 get its value last and bit1 getting its first
I believe that the cost works with a zero index, but I could be wrong

**Comment by CardboardBread** [comment]
I'm not sure I understand how to create a 3 bit signal from the modulo function, but it's similar to yours, so I thought it would work

**Comment by Vithop** [comment]
yeah what you said worked

**Comment by Vithop** [comment]
but i changed the circuit by getting rid of the transistors so now the mux is directly powering the led since it outputs 5v anyway
